// <auto-generated />
using System;
using EPS.Admisiones.Infrastructure.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPS.Admisiones.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(AdmisionesDbContext))]
    [Migration("20260801195724_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admisiones")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EPS.Admisiones.Domain.Admisiones.Admision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAdmisionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HistoriaClinicaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("IntentosSincronizacion")
                        .HasColumnType("int");

                    b.Property<string>("MotivoFallo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SincronizadaEnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Admisiones_Estado_Pendientes")
                        .HasFilter("[Estado] <> 2");

                    b.HasIndex("FechaAdmisionUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Admisiones_FechaAdmisionUtc");

                    b.HasIndex("HistoriaClinicaId")
                        .IsUnique()
                        .HasDatabaseName("UX_Admisiones_HistoriaClinicaId");

                    b.ToTable("Admisiones", "admisiones");
                });

            modelBuilder.Entity("EPS.Admisiones.Domain.Pacientes.Atencion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdmisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiereAuditoria")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdmisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Atenciones_AdmisionId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("RequiereAuditoria", "FechaUtc")
                        .HasDatabaseName("IX_Atenciones_Auditoria_Fecha");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("RequiereAuditoria", "FechaUtc"), new[] { "PacienteId" });

                    b.ToTable("Atenciones", "admisiones");
                });

            modelBuilder.Entity("EPS.Admisiones.Domain.Pacientes.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes", "admisiones");
                });

            modelBuilder.Entity("EPS.Admisiones.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisponibleDesdeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcesadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DisponibleDesdeUtc", "CreadoEnUtc")
                        .HasDatabaseName("IX_Outbox_Pendientes")
                        .HasFilter("[ProcesadoEnUtc] IS NULL");

                    b.ToTable("OutboxMessages", "admisiones");
                });

            modelBuilder.Entity("EPS.Admisiones.Domain.Admisiones.Admision", b =>
                {
                    b.OwnsOne("EPS.Admisiones.Domain.Admisiones.ValueObjects.ValorCopago", "Copago", b1 =>
                        {
                            b1.Property<Guid>("AdmisionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("MonedaCopago")
                                .IsFixedLength();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorCopago");

                            b1.HasKey("AdmisionId");

                            b1.ToTable("Admisiones", "admisiones");

                            b1.WithOwner()
                                .HasForeignKey("AdmisionId");
                        });

                    b.OwnsOne("EPS.Admisiones.Domain.Admisiones.ValueObjects.DocumentoPaciente", "Documento", b1 =>
                        {
                            b1.Property<Guid>("AdmisionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NumeroDocumento");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int")
                                .HasColumnName("TipoDocumento");

                            b1.HasKey("AdmisionId");

                            b1.ToTable("Admisiones", "admisiones");

                            b1.WithOwner()
                                .HasForeignKey("AdmisionId");
                        });

                    b.Navigation("Copago")
                        .IsRequired();

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("EPS.Admisiones.Domain.Pacientes.Atencion", b =>
                {
                    b.HasOne("EPS.Admisiones.Domain.Pacientes.Paciente", null)
                        .WithMany("Atenciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EPS.Admisiones.Domain.Admisiones.ValueObjects.ValorCopago", "Valor", b1 =>
                        {
                            b1.Property<Guid>("AtencionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nchar(3)")
                                .HasColumnName("Moneda")
                                .IsFixedLength();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("AtencionId");

                            b1.ToTable("Atenciones", "admisiones");

                            b1.WithOwner()
                                .HasForeignKey("AtencionId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("EPS.Admisiones.Domain.Pacientes.Paciente", b =>
                {
                    b.OwnsOne("EPS.Admisiones.Domain.Admisiones.ValueObjects.DocumentoPaciente", "Documento", b1 =>
                        {
                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NumeroDocumento");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int")
                                .HasColumnName("TipoDocumento");

                            b1.HasKey("PacienteId");

                            b1.HasIndex("Tipo", "Numero")
                                .IsUnique()
                                .HasDatabaseName("UX_Pacientes_Documento");

                            b1.ToTable("Pacientes", "admisiones");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("EPS.Admisiones.Domain.Pacientes.Paciente", b =>
                {
                    b.Navigation("Atenciones");
                });
#pragma warning restore 612, 618
        }
    }
}
